#!/usr/bin/env bash
#
# Bundle PythonSCAD's runtime Python dependencies (currently: IPython)
# into a destination directory that ships alongside a release binary.
#
# This script is the single source of truth for "what gets bundled into
# AppImage / macOS .app / Windows installer". Every binary distribution
# pipeline calls this script with a destination path that maps to one of
# the directories pythonscad's `initPython` searches at startup:
#
#   * AppImage   -> ${APPDIR}/usr/lib/pythonscad-bundled-py
#   * macOS .app -> <App>.app/Contents/Frameworks/pythonscad-bundled-py
#   * Windows    -> <staging>/lib/pythonscad-bundled-py
#
# The bundled directory is *appended* to sys.path inside `initPython`,
# which means a system-installed IPython (anything earlier on sys.path
# such as a venv, --user site, or distro package) wins over the bundle.
# The bundle is therefore strictly a fallback for self-contained binary
# distributions where the user has no other Python interpreter handy.
#
# Two artefacts are produced inside the destination directory:
#
#   1. The pip-installed packages from `requirements/runtime.txt`.
#   2. THIRD_PARTY_LICENSES.txt, generated by pip-licenses, which
#      enumerates the licenses of every bundled wheel. This file is
#      what the AppImage/.app/Installer ships next to its own COPYING.
#
# Usage:
#   bundle-runtime-python.sh <destination-dir> [--python <interpreter>]
#
# Required: destination-dir (created if missing).
# Optional: --python <interpreter>   pip target Python (default: python3)
#           --requirements <file>    override requirements file path
#           --no-licenses            skip THIRD_PARTY_LICENSES.txt step
#
# Exit codes:
#   0  success
#   1  unrecoverable error (bad arguments, pip install failed, ...)
#   2  pip-licenses missing AND --no-licenses not given. The license
#      file is mandatory for redistributable bundles, so the script
#      refuses to proceed silently. CI installs pip-licenses up front.

set -euo pipefail

readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly NC='\033[0m'

info()  { echo -e "${GREEN}[bundle-py]${NC} $*"; }
warn()  { echo -e "${YELLOW}[bundle-py]${NC} $*" >&2; }
error() { echo -e "${RED}[bundle-py]${NC} $*" >&2; }
die()   { error "$*"; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

DEST=""
PYTHON_BIN="${PYTHON:-python3}"
REQUIREMENTS="${PROJECT_ROOT}/requirements/runtime.txt"
WITH_LICENSES=1

while [[ $# -gt 0 ]]; do
    case "$1" in
        --python)
            # `set -u` would otherwise turn a missing value into a
            # cryptic "unbound variable" error; the explicit check
            # gives the user a clear usage message instead.
            [[ $# -ge 2 ]] || die "missing value for --python"
            PYTHON_BIN="$2"
            shift 2
            ;;
        --requirements)
            [[ $# -ge 2 ]] || die "missing value for --requirements"
            REQUIREMENTS="$2"
            shift 2
            ;;
        --no-licenses)
            WITH_LICENSES=0
            shift
            ;;
        -h|--help)
            sed -n '2,40p' "$0"
            exit 0
            ;;
        --*)
            die "unknown option: $1"
            ;;
        *)
            if [[ -z "${DEST}" ]]; then
                DEST="$1"
            else
                die "unexpected positional argument: $1"
            fi
            shift
            ;;
    esac
done

[[ -n "${DEST}" ]] || die "destination directory is required"
[[ -f "${REQUIREMENTS}" ]] || die "requirements file not found: ${REQUIREMENTS}"
command -v "${PYTHON_BIN}" >/dev/null 2>&1 \
    || die "python interpreter not found: ${PYTHON_BIN}"

info "Bundling runtime Python deps:"
info "  destination:  ${DEST}"
info "  interpreter:  ${PYTHON_BIN} ($("${PYTHON_BIN}" --version 2>&1))"
info "  requirements: ${REQUIREMENTS}"

mkdir -p "${DEST}"

# Step 1: install the runtime requirements into the destination.
#
# `--target` lays the wheels out flat (no venv structure) which is what
# the embedded interpreter expects when this directory is added to
# sys.path. `--upgrade` handles re-runs cleanly.
info "Running pip install --target=${DEST} -r ${REQUIREMENTS}"
"${PYTHON_BIN}" -m pip install \
    --target "${DEST}" \
    --upgrade \
    --no-compile \
    -r "${REQUIREMENTS}" \
    || die "pip install into ${DEST} failed"

# Step 2: emit THIRD_PARTY_LICENSES.txt next to the bundled wheels.
#
# We point pip-licenses at the destination directory so the report
# reflects exactly what we shipped, not whatever happens to be in the
# build host's site-packages. This also avoids polluting the CI build
# environment with extra packages.
if [[ "${WITH_LICENSES}" -eq 1 ]]; then
    if ! "${PYTHON_BIN}" -c "import piplicenses" >/dev/null 2>&1; then
        # `pip-licenses` is intentionally NOT in requirements/runtime.txt
        # (it is a build-time tool, not a runtime dependency the user's
        # scripts can import). Distributors must install it themselves;
        # CI does this in the workflow step that calls us.
        if [[ "${BUNDLE_PY_AUTO_INSTALL_PIP_LICENSES:-0}" = "1" ]]; then
            warn "pip-licenses missing; auto-installing because BUNDLE_PY_AUTO_INSTALL_PIP_LICENSES=1"
            "${PYTHON_BIN}" -m pip install --quiet pip-licenses \
                || die "auto-install of pip-licenses failed"
        else
            error "pip-licenses is not installed in ${PYTHON_BIN}."
            error "Install it (e.g. 'pip install pip-licenses') or pass"
            error "--no-licenses to skip the bundled licenses report."
            exit 2
        fi
    fi

    LICENSES_OUT="${DEST}/THIRD_PARTY_LICENSES.txt"
    info "Generating ${LICENSES_OUT}"

    # Restrict pip-licenses to *only* the packages we installed under
    # ${DEST}. Two filters are in play:
    #
    #   1. We monkey-patch `importlib.metadata.distributions` so it
    #      yields only distributions whose on-disk location lives
    #      under ${DEST}. Without this, pip-licenses uses the build
    #      host's site-packages too (since `python -m piplicenses`
    #      runs with site.py initialized) and we'd ship a license
    #      report that conflates bundled and host wheels - making
    #      the "drift detector" intent unreliable.
    #   2. We *also* pass `--packages` enumerated from the bundle's
    #      `*.dist-info` directories. This is belt-and-suspenders:
    #      if (1) ever regresses, (2) still keeps the package list
    #      bounded.
    BUNDLED_PACKAGES=()
    while IFS= read -r -d '' dist_info; do
        # `package-1.2.3.dist-info` -> `package`. Pip canonicalizes
        # names with `-` separators and lowercase, but pip-licenses
        # accepts the original PEP 503-normalized form fine.
        pkg_name="$(basename "${dist_info}")"
        pkg_name="${pkg_name%.dist-info}"
        pkg_name="${pkg_name%-*}"
        BUNDLED_PACKAGES+=("${pkg_name}")
    done < <(find "${DEST}" -maxdepth 2 -name "*.dist-info" -type d -print0 2>/dev/null)

    if [[ ${#BUNDLED_PACKAGES[@]} -eq 0 ]]; then
        die "no .dist-info directories found under ${DEST}; cannot generate license report"
    fi

    info "Reporting on ${#BUNDLED_PACKAGES[@]} bundled package(s): ${BUNDLED_PACKAGES[*]}"

    # `mktemp --suffix=.py` is a GNU extension; macOS ships BSD
    # mktemp which doesn't accept --suffix. Use a portable template
    # under $TMPDIR (or /tmp) and rename to add the .py extension
    # so Python recognises the file as a script.
    PIP_LICENSES_WRAPPER_BASE="$(mktemp "${TMPDIR:-/tmp}/bundle-py-piplic-XXXXXXXX")"
    PIP_LICENSES_WRAPPER="${PIP_LICENSES_WRAPPER_BASE}.py"
    mv "${PIP_LICENSES_WRAPPER_BASE}" "${PIP_LICENSES_WRAPPER}"

    cat > "${PIP_LICENSES_WRAPPER}" <<'WRAPPER_EOF'
"""Run pip-licenses scoped to a single sys.path target directory.

Argument vector layout:
    sys.argv = [<this file>, <target_dir>, <pip-licenses args...>]

The wrapper:
  1. Inserts <target_dir> at sys.path[0] so pip-licenses imports
     (and reads METADATA / LICENSE files from) the bundled wheels
     in preference to any older host copies of the same name. This
     replaces a previous `PYTHONPATH=...` shell-side approach which
     was non-portable across `:`-separator (POSIX) and `;`-separator
     (Windows native Python) hosts.
  2. Monkey-patches importlib.metadata.distributions to yield only
     distributions whose installed files live under <target_dir>,
     so the host's site-packages don't leak into the report.
  3. Hands off to piplicenses.main() with the remaining argv.
"""
import os
import sys
import importlib.metadata as md

target_dir = os.path.realpath(sys.argv[1])
sys.argv[1:] = sys.argv[2:]

# Step (1): make the bundle preferred for any imports pip-licenses
# does on its own (e.g. reading wheel metadata via importlib).
if target_dir not in sys.path:
    sys.path.insert(0, target_dir)

# Step (2): scope distribution enumeration to the bundle.
_real_distributions = md.distributions


def _scoped_distributions(*args, **kwargs):
    for dist in _real_distributions(*args, **kwargs):
        loc = dist.locate_file("")
        try:
            loc_str = os.path.realpath(str(loc))
        except (TypeError, ValueError):
            continue
        if loc_str.startswith(target_dir + os.sep) or loc_str == target_dir:
            yield dist


md.distributions = _scoped_distributions

# pip-licenses 4.x and 5.x both expose `main` at module top-level.
from piplicenses import main as piplicenses_main  # noqa: E402

sys.exit(piplicenses_main() or 0)
WRAPPER_EOF

    "${PYTHON_BIN}" \
        "${PIP_LICENSES_WRAPPER}" \
        "${DEST}" \
        --from=mixed \
        --format=plain-vertical \
        --with-license-file \
        --with-urls \
        --with-authors \
        --no-license-path \
        --packages "${BUNDLED_PACKAGES[@]}" \
        --output-file "${LICENSES_OUT}" \
        || { rm -f "${PIP_LICENSES_WRAPPER}"; die "pip-licenses failed to generate ${LICENSES_OUT}"; }
    rm -f "${PIP_LICENSES_WRAPPER}"

    # Prepend a header that pins down what the file is. pip-licenses
    # itself only emits raw entries; consumers reading
    # THIRD_PARTY_LICENSES.txt deserve a one-paragraph explanation.
    HEADER_FILE="$(mktemp)"
    cat > "${HEADER_FILE}" <<'HEADER_EOF'
THIRD-PARTY LICENSES
====================

This file lists the licenses of the third-party Python packages
bundled inside this PythonSCAD distribution under the
"pythonscad-bundled-py" directory. The list is generated automatically
at build time by scripts/bundle-runtime-python.sh and reflects the
exact wheels shipped alongside the binary.

PythonSCAD itself is licensed under the GNU General Public License
v2 or later; see the COPYING file shipped next to this report.

----------------------------------------------------------------------

HEADER_EOF
    cat "${HEADER_FILE}" "${LICENSES_OUT}" > "${LICENSES_OUT}.tmp"
    mv "${LICENSES_OUT}.tmp" "${LICENSES_OUT}"
    rm -f "${HEADER_FILE}"
fi

# Sanity-check: the bundle must at least be importable as `IPython`.
#
# We pass the bundle directory in via argv and have the smoke probe
# insert it into sys.path itself rather than relying on PYTHONPATH.
# PYTHONPATH uses `:` as the separator on POSIX and `;` on Windows
# native Python; doing the path-mutation in Python makes the call
# site cross-platform without any per-host quoting tricks.
info "Smoke-checking bundle (import IPython)"
"${PYTHON_BIN}" - "${DEST}" <<'PY' || die "bundle smoke check failed"
import sys
sys.path.insert(0, sys.argv[1])
import IPython
print("[bundle-py] bundled IPython:", IPython.__version__, "from", IPython.__file__)
PY

info "Bundle complete: $(du -sh "${DEST}" | cut -f1) at ${DEST}"
