"""Regression fixture for the in-script ``export()`` function: POV-Ray.

The ``.pov`` suffix routes through ``fileformat::fromIdentifier()`` to
``FileFormat::POV`` in ``python_export_core()``. POV's ``Generated by``
header uses ``EXPORT_CREATOR`` (PythonSCAD); the driver runs
``post_process_progname`` (registered via ``_POST_PROCESSORS[".pov"]``)
to rewrite that branding to the OpenSCAD-shaped golden before compare.
"""
from pythonscad import cube, export

export(cube(5), "cube.pov")
