name: Test Cairo pkg-config

on:
  pull_request:
  workflow_dispatch:

jobs:
  check-cairo:
    name: Check Cairo Package
    runs-on: windows-latest

    steps:
      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
          cd C:\vcpkg
          git checkout 74e6536215718009aae747d86d84b78376bf9e09
          bootstrap-vcpkg.bat
        shell: cmd

      - name: Install Cairo
        run: |
          C:\vcpkg\vcpkg.exe install cairo:x64-windows
        shell: cmd

      - name: Check Cairo Installation
        run: |
          echo "=== Checking Cairo installation ==="
          echo ""
          echo "Listing installed files:"
          dir C:\vcpkg\installed\x64-windows\ /s /b | findstr /i cairo
          echo ""
          echo "=== Checking for .pc files ==="
          dir C:\vcpkg\installed\x64-windows\lib\pkgconfig\*.pc
          echo ""
          echo "=== Checking pkgconf tool ==="
          dir C:\vcpkg\installed\x64-windows\tools\pkgconf\
          echo ""
          echo "=== Testing pkg-config with pkgconf ==="
          set PKG_CONFIG_PATH=C:\vcpkg\installed\x64-windows\lib\pkgconfig
          C:\vcpkg\installed\x64-windows\tools\pkgconf\pkgconf.exe --modversion cairo
          echo ""
          echo "=== Complete ==="
        shell: cmd
